services:
  homehub-api:
    build:
      context: ../HomeHubApplication
      dockerfile: Dockerfile
    ports:
      - "7080:8080"
      - "7443:8443"
    networks:
      - homehub-network

networks:
  homehub-network:
    name: homehub-network
    external: true
    # environment:
    #   - ConnectionStrings__DefaultConnection=${CONNECTIONSTRING}
    #   - Auth__IdentityProviderUrl=${Auth__IdentityProviderUrl}